autolabeler:
  - label: "feature"
    branch:
      - '/feat\/.+/'
  - label: "chore"
    files:
      - "*.md"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "dependencies"
    title:
      - "/^Bump.+/"
template: |
  ## Changes

  $CHANGES
