autolabeler:
  - label: "feature"
    branch:
      - '/feat\/.+/'
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "dependencies"
    title:
      - "/^Bump.+/"

  - label: "minor"
    branch:
      - '/feat\/.+/'
  - label: "patch"
    branch:
      - '/chore\/.+/'
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Features"
    labels:
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Maintenance"
    label: "chore"
  - title: "Dependencies"
    label: "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
