_extends: test-monorepo-release-drafter:.github/release-drafter-base.yml
include-paths:
  - "apps/app-a/"
  - "packages/"
name-template: app-a@$RESOLVED_VERSION
tag-template: app-a@$RESOLVED_VERSION
tag-prefix: app-a@
