autolabeler:
  - label: "feature"
    branch:
      - '/^feat.*\/.+/'
  - label: "refactor"
    branch:
      - '/refactor\/.+/'
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "app:app-a"
    files:
      - "apps/app-a/**/*"
      - "packages/**/*"
  - label: "app:app-b"
    files:
      - "apps/app-b/**/*"
      - "packages/**/*"
categories:
  - title: "Features"
    labels:
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Refactors"
    labels:
      - "refactor"
  - title: "Chores"
    labels:
      - "chore"
      - "dependencies"
    collapse-after: 5
  - title: "Other changes"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
sort-direction: ascending
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "refactor"
      - "chore"
      - "bug"
      - "dependencies"
  default: patch
template: |
  $CHANGES
