_extends: test-monorepo-release-drafter:.github/release-drafter/base.yml
include-paths:
  - "apps/app-b/"
  - "packages/"
name-template: app-b@$RESOLVED_VERSION
tag-template: app-b@$RESOLVED_VERSION
tag-prefix: app-b@
footer: |

  ---
  **Full Changelog:** [$PREVIOUS_TAG...app-b@$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...app-b@$RESOLVED_VERSION)
